id = "cannot-create-closure-as-attribute-argument"
error = "Cannot create Closure as attribute argument"
phpVersion = "8.1+"
level = "E_COMPILE_ERROR"
exception = ""
code = "<?php

#[Foo(...)]
function goo() {}

?>"
description = "It is possible to use ``...`` in a function call, but not as an attribute, as it leads to create a PHP closure, which does not carry the Attribute attribute (sic). It also makes little sense, though the PHP parser accepts it, but not the linter."
alternative[] = "Remove the three dots from the attribute."
related[] = ""
examples[] = ""
tags[] = "attribute"
tags[] = "closure"
seeAlso[] = ""
features[] = "attribute"
features[] = "first-class-callable"
features[] = "closure"
previous = ""
next = ""
extension[] = ""
analyzer[] = ""
changedBehavior[] = ""